#!/bin/bash

sudo apt-get clean && sudo apt-get autoclean && zenity --info --title "Clean" --text "Cache di apt svuotata." \
|| zenity --warning --title "Clean" --text "La pulizia della cache avuto un esito negativo."

sudo apt-get --purge autoremove && zenity --info --title "Autoremove" --text "Pacchetti inutilizzati eliminati." \
|| zenity --warning --title "Clean" --text "La pulizia della cache avuto un esito negativo."
